FROM ghcr.io/astral-sh/uv:0.11.29 AS uv
FROM gradle:9.4.1-jdk17

COPY --from=uv /uv /uvx /usr/local/bin/

ENV UV_PYTHON_INSTALL_DIR=/opt/uv-python

RUN uv python install 3.14 \
    && ln -s "$(uv python find 3.14)" /usr/local/bin/python3.14
