name: Build Android APK

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Run Android pipeline
        uses: ./.ci-cd/android
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
