name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Docker pipeline
        uses: ./.ci-cd/docker
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
